2024-09-29 10:08:50,355 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:08:58,936 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:09:06,935 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:09:11,114 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:10:00,583 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:10:07,765 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:10:21,709 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:10:34,411 (WARNING) - silk.model_factory - Response to request with pk aef8375d-a969-47dc-b7a1-f044e55398c3 has content type text/javascript but was unable to parse it
2024-09-29 10:10:38,081 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:11:08,785 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:11:43,330 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:12:11,622 (WARNING) - silk.model_factory - Response to request with pk bc7d2b77-78c6-4f24-a3bb-139e8a019abb has content type text/javascript but was unable to parse it
2024-09-29 10:12:15,237 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:14:03,275 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:14:21,196 (WARNING) - silk.model_factory - Response to request with pk 5aaac97e-2575-4de1-82ee-10334ae549e5 has content type text/javascript but was unable to parse it
2024-09-29 10:14:24,931 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:14:41,045 (WARNING) - silk.model_factory - Response to request with pk 868bdf15-583c-4c69-b585-229ff0bbeaf8 has content type text/javascript but was unable to parse it
2024-09-29 10:14:44,944 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:15:10,989 (WARNING) - silk.model_factory - Response to request with pk b89a3330-dd52-4cb1-9d33-c2931d2da55d has content type text/javascript but was unable to parse it
2024-09-29 10:15:14,802 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:16:38,748 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/settings/dev.py changed, reloading.
2024-09-29 10:16:39,147 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:17:03,567 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/settings/dev.py changed, reloading.
2024-09-29 10:17:03,883 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:19:16,353 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/settings/dev.py changed, reloading.
2024-09-29 10:19:16,751 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:19:25,904 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:19:33,029 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:19:38,250 (WARNING) - silk.model_factory - Response to request with pk 9f0fd9b3-0734-4f63-80d2-edac050de87d has content type text/javascript but was unable to parse it
2024-09-29 10:19:41,925 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:21:00,696 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/settings/common.py changed, reloading.
2024-09-29 10:21:01,123 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:21:08,763 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/settings/common.py changed, reloading.
2024-09-29 10:21:09,145 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:21:31,066 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/settings/dev.py changed, reloading.
2024-09-29 10:21:31,454 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:21:40,098 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:21:44,588 (WARNING) - silk.model_factory - Response to request with pk dd5a6f0f-498d-4006-89ff-d73601e9138e has content type text/javascript but was unable to parse it
2024-09-29 10:21:48,783 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:21:52,647 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:21:57,838 (WARNING) - silk.model_factory - Response to request with pk db2034a0-55f5-4c99-b85d-c337487a316e has content type text/javascript but was unable to parse it
2024-09-29 10:22:01,857 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:24:20,491 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/urls.py changed, reloading.
2024-09-29 10:24:20,966 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:24:27,481 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:24:49,304 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:24:55,065 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:25:01,023 (WARNING) - silk.model_factory - Response to request with pk 9c2da280-99df-456a-b551-c69baf4e6db9 has content type text/javascript but was unable to parse it
2024-09-29 10:25:04,977 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:36:36,542 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:36:48,136 (WARNING) - silk.model_factory - Response to request with pk b2704cae-fab3-4ff3-b331-f4e2a04f2670 has content type text/javascript but was unable to parse it
2024-09-29 10:36:52,243 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:37:05,376 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:37:12,080 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:37:16,724 (WARNING) - silk.model_factory - Response to request with pk a51da46f-3d06-43d0-aa76-a53534f2b49e has content type text/javascript but was unable to parse it
2024-09-29 10:37:20,872 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:37:49,349 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:38:11,237 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:38:23,701 (WARNING) - django.request - Not Found: /favicon.ico
2024-09-29 10:41:46,923 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/settings/dev.py changed, reloading.
2024-09-29 10:41:47,353 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:42:06,018 (WARNING) - silk.model_factory - Response to request with pk e0f425c0-0ddf-4f5c-b0df-ec984fb1d326 has content type text/javascript but was unable to parse it
2024-09-29 10:42:56,949 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/settings/dev.py changed, reloading.
2024-09-29 10:42:57,398 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:44:34,803 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:44:44,758 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:44:53,035 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:46:19,487 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/settings/dev.py changed, reloading.
2024-09-29 10:46:19,970 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 10:46:52,590 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 10:47:39,665 (WARNING) - silk.model_factory - Response to request with pk 62bf6ab8-e7ec-464f-9ee1-39e58109e3a1 has content type text/javascript but was unable to parse it
2024-09-29 11:02:03,348 (WARNING) - silk.model_factory - Response to request with pk 1fbd368e-87bb-4a10-a4c8-9b89906ba1d5 has content type text/javascript but was unable to parse it
2024-09-29 11:02:07,736 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 11:16:29,039 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 11:16:29,155 (WARNING) - django.request - Not Found: /favicon.ico
2024-09-29 11:35:09,216 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 11:35:55,087 (WARNING) - django.request - Not Found: /cart.json
2024-09-29 11:36:15,955 (WARNING) - django.request - Not Found: /favicon.ico
2024-09-29 12:28:08,098 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-29 12:28:17,644 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 05:46:40,273 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 05:46:44,974 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 05:46:45,026 (WARNING) - django.request - Not Found: /favicon.ico
2024-09-30 15:58:19,308 (ERROR) - django.request - Internal Server Error: /
Traceback (most recent call last):
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
2024-09-30 15:58:20,176 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:01:12,615 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:01:14,828 (WARNING) - django.request - Method Not Allowed (POST): /
2024-09-30 16:01:14,843 (WARNING) - django.request - Method Not Allowed: /
2024-09-30 16:01:21,166 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:01:25,413 (WARNING) - django.request - Method Not Allowed (POST): /
2024-09-30 16:01:25,427 (WARNING) - django.request - Method Not Allowed: /
2024-09-30 16:02:45,893 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:02:46,966 (WARNING) - django.request - Method Not Allowed (POST): /
2024-09-30 16:02:46,980 (WARNING) - django.request - Method Not Allowed: /
2024-09-30 16:02:53,089 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:03:14,139 (WARNING) - django.request - Method Not Allowed (POST): /
2024-09-30 16:03:14,153 (WARNING) - django.request - Method Not Allowed: /
2024-09-30 16:07:40,815 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:07:41,936 (WARNING) - django.request - Method Not Allowed (POST): /
2024-09-30 16:07:41,950 (WARNING) - django.request - Method Not Allowed: /
2024-09-30 16:07:46,064 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:07:47,720 (WARNING) - django.request - Method Not Allowed (POST): /
2024-09-30 16:07:47,735 (WARNING) - django.request - Method Not Allowed: /
2024-09-30 16:07:51,664 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:10:26,025 (WARNING) - django.request - Method Not Allowed (POST): /
2024-09-30 16:10:26,040 (WARNING) - django.request - Method Not Allowed: /
2024-09-30 16:12:30,238 (WARNING) - django.request - Method Not Allowed (POST): /
2024-09-30 16:12:30,253 (WARNING) - django.request - Method Not Allowed: /
2024-09-30 16:12:42,691 (WARNING) - django.request - Method Not Allowed (POST): /
2024-09-30 16:12:42,705 (WARNING) - django.request - Method Not Allowed: /
2024-09-30 16:12:58,278 (WARNING) - django.request - Method Not Allowed (POST): /
2024-09-30 16:12:58,292 (WARNING) - django.request - Method Not Allowed: /
2024-09-30 16:13:55,257 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/urls.py changed, reloading.
2024-09-30 16:13:55,809 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 16:14:05,482 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/views.py changed, reloading.
2024-09-30 16:14:05,963 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 16:14:20,851 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:14:22,718 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:14:26,796 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:14:27,949 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:14:29,246 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:14:30,400 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:15:04,232 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:15:06,197 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:15:10,295 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:16:53,414 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/views.py changed, reloading.
2024-09-30 16:16:53,902 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 16:17:20,602 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:17:22,768 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:17:24,505 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:18:01,099 (WARNING) - django.request - Not Found: /favicon.ico
2024-09-30 16:18:44,737 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/views.py changed, reloading.
2024-09-30 16:18:45,215 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 16:18:58,274 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:19:00,125 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:19:14,084 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:19:17,110 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:20:53,600 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:21:01,382 (ERROR) - django.request - Internal Server Error: /
Traceback (most recent call last):
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/views.py", line 15, in index
    return redirect('home')  # Replace 'home' with the actual URL you want to redirect to
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
2024-09-30 16:21:01,576 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:21:14,634 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:21:16,199 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:21:23,747 (ERROR) - django.request - Internal Server Error: /
Traceback (most recent call last):
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/views.py", line 15, in index
    return redirect('home')  # Replace 'home' with the actual URL you want to redirect to
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/Users/arnoldaskaralius/PycharmProjects/amadesa/venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
2024-09-30 16:21:23,935 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:22:13,956 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/urls.py changed, reloading.
2024-09-30 16:22:14,426 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 16:27:18,893 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/urls.py changed, reloading.
2024-09-30 16:27:19,337 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 16:27:23,635 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/urls.py changed, reloading.
2024-09-30 16:27:24,056 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 16:27:33,531 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/views.py changed, reloading.
2024-09-30 16:27:34,025 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 16:28:19,089 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:28:21,279 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:28:26,116 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:29:17,517 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/views.py changed, reloading.
2024-09-30 16:29:17,984 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 16:29:53,059 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/urls.py changed, reloading.
2024-09-30 16:29:53,491 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 16:30:15,106 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:30:16,973 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:30:21,939 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:38:32,654 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:38:34,799 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:38:37,102 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:38:39,011 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:39:18,672 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:41:11,395 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:41:17,444 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:41:27,729 (WARNING) - silk.model_factory - Response to request with pk 2441595e-777a-4b78-b451-1fda0d2f38d1 has content type text/javascript but was unable to parse it
2024-09-30 16:41:28,792 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:41:31,075 (WARNING) - silk.model_factory - Response to request with pk ca69b758-4fda-4924-bdd8-d6d66f59a39b has content type text/javascript but was unable to parse it
2024-09-30 16:41:31,319 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:43:04,570 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:43:05,933 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:43:09,125 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:43:15,262 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:43:16,881 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:43:26,280 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:43:32,142 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:49:10,169 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:53:18,755 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:53:26,359 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:56:17,022 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:56:27,603 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 16:56:34,276 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:07:57,096 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/urls.py changed, reloading.
2024-09-30 17:07:57,594 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 17:09:58,171 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/storefront/settings/common.py changed, reloading.
2024-09-30 17:09:58,593 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 17:10:25,689 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:10:27,217 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:10:28,284 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:10:29,125 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:10:29,678 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:10:30,533 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:10:31,218 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:10:31,909 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:10:32,519 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:10:33,903 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:10:35,368 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:10:36,987 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:11:39,224 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/core/apps.py changed, reloading.
2024-09-30 17:11:39,739 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 17:12:16,514 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:12:16,697 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:12:17,849 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:13:50,688 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:13:51,674 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:15:52,585 (INFO) - django.utils.autoreload - /Users/arnoldaskaralius/PycharmProjects/amadesa/storefront/foundation/admin.py changed, reloading.
2024-09-30 17:15:53,073 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 17:16:30,808 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:16:33,166 (WARNING) - silk.model_factory - Response to request with pk 6e1ad325-f88d-474b-95b0-d52c0a0b36a0 has content type text/javascript but was unable to parse it
2024-09-30 17:16:33,934 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 17:16:43,673 (WARNING) - silk.model_factory - Response to request with pk 1df0699c-7504-4a15-873d-4f844116255a has content type text/javascript but was unable to parse it
2024-09-30 17:16:43,794 (WARNING) - django.request - Not Found: /cart.json
2024-09-30 22:52:21,830 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 22:52:29,878 (WARNING) - django.request - Not Found: /favicon.ico
2024-09-30 23:08:30,720 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:08:35,429 (WARNING) - django.request - Not Found: /favicon.ico
2024-09-30 23:19:15,512 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:19:16,337 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:19:33,375 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:19:34,221 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:20:04,113 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:20:05,002 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:20:27,412 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:20:28,192 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:20:54,950 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:20:55,692 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:23:00,751 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:23:01,523 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:25:25,512 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:25:26,217 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:26:45,333 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:26:46,140 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:27:22,524 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\serializers.py changed, reloading.
2024-09-30 23:27:23,346 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:27:35,098 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\serializers.py changed, reloading.
2024-09-30 23:27:35,893 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:29:52,225 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\serializers.py changed, reloading.
2024-09-30 23:29:53,000 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:30:22,935 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\views.py changed, reloading.
2024-09-30 23:30:23,747 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:30:39,672 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\urls.py changed, reloading.
2024-09-30 23:30:40,420 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:30:52,141 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\urls.py changed, reloading.
2024-09-30 23:30:52,914 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:32:45,061 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\serializers.py changed, reloading.
2024-09-30 23:32:45,855 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:33:51,094 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-09-30 23:33:51,870 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:48:32,004 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:48:32,773 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:49:21,251 (WARNING) - django.request - Not Found: /favicon.ico
2024-09-30 23:51:08,575 (WARNING) - silk.model_factory - Response to request with pk 08b5113b-ce68-4d44-be08-bac6ee9766e4 has content type text/javascript but was unable to parse it
2024-09-30 23:51:14,750 (WARNING) - silk.model_factory - Response to request with pk e5589218-42a4-454e-b556-c2f09b6746cf has content type text/javascript but was unable to parse it
2024-09-30 23:51:20,087 (WARNING) - silk.model_factory - Response to request with pk 88117a75-0b67-4957-8a6b-71ade540a7cc has content type text/javascript but was unable to parse it
2024-09-30 23:52:36,126 (WARNING) - silk.model_factory - Response to request with pk 491b3b60-375c-4bee-9023-9f9cb97a46ba has content type text/javascript but was unable to parse it
2024-09-30 23:53:02,286 (WARNING) - silk.model_factory - Response to request with pk da7e7a78-594e-42fa-9b8c-7bfdb324d8fd has content type text/javascript but was unable to parse it
2024-09-30 23:54:31,163 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:54:31,976 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:54:56,615 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:54:57,374 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:55:52,885 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:55:53,616 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:56:44,922 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:56:45,705 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:57:20,929 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:57:21,715 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:57:29,197 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-09-30 23:57:29,961 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:58:11,594 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-09-30 23:58:12,321 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-09-30 23:58:59,347 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-09-30 23:59:00,091 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:00:09,272 (WARNING) - silk.model_factory - Response to request with pk 6d286603-984f-4ba7-8cd3-3d53a843c46f has content type text/javascript but was unable to parse it
2024-10-01 00:00:12,906 (WARNING) - silk.model_factory - Response to request with pk 4bb85f88-0898-459c-ac52-3741d15fa16f has content type text/javascript but was unable to parse it
2024-10-01 00:00:17,775 (WARNING) - silk.model_factory - Response to request with pk ab8203ce-da8b-4631-860f-44294f0090f5 has content type text/javascript but was unable to parse it
2024-10-01 00:02:25,552 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-10-01 00:02:26,422 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:02:29,803 (WARNING) - silk.model_factory - Response to request with pk d9fbece9-a97f-4904-9c63-1e0e526980bd has content type text/javascript but was unable to parse it
2024-10-01 00:02:32,560 (WARNING) - silk.model_factory - Response to request with pk e5bc0704-864a-4e5f-8ee5-b439a9eed9a3 has content type text/javascript but was unable to parse it
2024-10-01 00:02:34,675 (WARNING) - silk.model_factory - Response to request with pk bc1b6898-b87a-4b59-a10b-f03f87e55a79 has content type text/javascript but was unable to parse it
2024-10-01 00:02:45,398 (WARNING) - silk.model_factory - Response to request with pk a6435a7f-08f1-4f19-b30b-1c2f920cf080 has content type text/javascript but was unable to parse it
2024-10-01 00:02:48,151 (WARNING) - silk.model_factory - Response to request with pk a69d6526-6e14-4f78-b598-e39a1adbc101 has content type text/javascript but was unable to parse it
2024-10-01 00:02:53,661 (WARNING) - silk.model_factory - Response to request with pk c8aec6ab-cdef-4eb7-ab8a-579ffc525408 has content type text/javascript but was unable to parse it
2024-10-01 00:02:56,066 (WARNING) - silk.model_factory - Response to request with pk 31a97423-3061-47d4-9ab5-9b2711f94bd7 has content type text/javascript but was unable to parse it
2024-10-01 00:03:02,009 (WARNING) - silk.model_factory - Response to request with pk 88a26430-0eff-4741-b189-d767d424cd7c has content type text/javascript but was unable to parse it
2024-10-01 00:03:10,208 (WARNING) - silk.model_factory - Response to request with pk dcd99481-6c43-4d5a-8478-66737d98c22c has content type text/javascript but was unable to parse it
2024-10-01 00:04:05,254 (WARNING) - silk.model_factory - Response to request with pk 5c54f12a-a0ab-4e5c-b025-8d1d7a10c044 has content type text/javascript but was unable to parse it
2024-10-01 00:04:11,853 (WARNING) - silk.model_factory - Response to request with pk 2ddec9b6-23cf-415e-8609-d526235d0a6d has content type text/javascript but was unable to parse it
2024-10-01 00:04:26,143 (WARNING) - silk.model_factory - Response to request with pk c62ecf78-c9c1-4c01-9027-fbe8480967c1 has content type text/javascript but was unable to parse it
2024-10-01 00:04:28,319 (WARNING) - silk.model_factory - Response to request with pk 2d2ee93d-50aa-45e1-9944-0f750786c0b1 has content type text/javascript but was unable to parse it
2024-10-01 00:06:53,059 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-10-01 00:06:53,906 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:06:59,986 (WARNING) - silk.model_factory - Response to request with pk dde15347-7c1c-4ff7-ba9a-fb5d93cf08f1 has content type text/javascript but was unable to parse it
2024-10-01 00:07:02,285 (WARNING) - silk.model_factory - Response to request with pk 45537464-409e-4f5d-946a-c850bd7bf227 has content type text/javascript but was unable to parse it
2024-10-01 00:07:04,608 (WARNING) - silk.model_factory - Response to request with pk d6e83bfc-5b2c-4baa-92df-4586090c409f has content type text/javascript but was unable to parse it
2024-10-01 00:07:07,498 (WARNING) - silk.model_factory - Response to request with pk f4bea519-8783-441e-8cb0-7f6cb38000ec has content type text/javascript but was unable to parse it
2024-10-01 00:07:09,944 (WARNING) - silk.model_factory - Response to request with pk 3048c158-6756-4cbb-bb6e-4f1fb4cb2a53 has content type text/javascript but was unable to parse it
2024-10-01 00:07:16,275 (WARNING) - silk.model_factory - Response to request with pk d7dad324-71c9-4f07-87cd-efbe67811d28 has content type text/javascript but was unable to parse it
2024-10-01 00:07:20,573 (WARNING) - silk.model_factory - Response to request with pk 1aaef767-0df5-4a43-b1ca-2541d2ff5854 has content type text/javascript but was unable to parse it
2024-10-01 00:07:24,451 (WARNING) - silk.model_factory - Response to request with pk ef25ed27-3027-4e8f-bee6-d3bf067d56a4 has content type text/javascript but was unable to parse it
2024-10-01 00:07:26,313 (WARNING) - silk.model_factory - Response to request with pk 5424bd22-cca6-4e24-916e-6d1ca2fbf65a has content type text/javascript but was unable to parse it
2024-10-01 00:07:56,445 (WARNING) - silk.model_factory - Response to request with pk 432703ad-0d18-461e-b45f-99838b1edc74 has content type text/javascript but was unable to parse it
2024-10-01 00:08:12,512 (WARNING) - silk.model_factory - Response to request with pk 3ab445cb-8bd5-4849-8304-d317f1ac2888 has content type text/javascript but was unable to parse it
2024-10-01 00:08:15,638 (WARNING) - silk.model_factory - Response to request with pk 67b9439a-1506-48b3-aa65-efc92f15215d has content type text/javascript but was unable to parse it
2024-10-01 00:09:12,797 (WARNING) - silk.model_factory - Response to request with pk 45ad8c9e-70ae-4995-b474-3c28cc5b316b has content type text/javascript but was unable to parse it
2024-10-01 00:10:34,555 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-10-01 00:10:35,403 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:12:00,479 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:12:28,180 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\views.py changed, reloading.
2024-10-01 00:12:28,973 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:13:08,581 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-10-01 00:13:09,357 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:13:38,178 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-10-01 00:13:38,908 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:14:01,251 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-10-01 00:14:02,016 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:14:45,852 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-10-01 00:14:46,614 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:15:22,360 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-10-01 00:15:23,075 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:15:51,587 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\models.py changed, reloading.
2024-10-01 00:15:52,314 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:15:59,695 (WARNING) - silk.model_factory - Response to request with pk 9b50a25e-b690-40b3-808a-d7d6b6baa834 has content type text/javascript but was unable to parse it
2024-10-01 00:16:01,004 (ERROR) - django.request - Internal Server Error: /admin/foundation/language/2/change/
Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 89, in execute_sql
    return self._execute_sql(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1964, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1919, in _changeform_view
    media += inline_formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\helpers.py", line 465, in media
    media = self.opts.media + self.formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 521, in media
    if self.forms:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 207, in forms
    for i in range(self.total_form_count())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 182, in total_form_count
    initial_forms = self.initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 1123, in initial_form_count
    return super().initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 697, in initial_form_count
    return len(self.get_queryset())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 96, in execute_sql
    query_dict['analysis'] = _explain_query(self.connection, q, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 58, in _explain_query
    cur.execute(prefixed_query, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block

2024-10-01 00:21:56,731 (ERROR) - django.request - Internal Server Error: /admin/foundation/language/2/change/
Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 89, in execute_sql
    return self._execute_sql(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1964, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1919, in _changeform_view
    media += inline_formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\helpers.py", line 465, in media
    media = self.opts.media + self.formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 521, in media
    if self.forms:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 207, in forms
    for i in range(self.total_form_count())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 182, in total_form_count
    initial_forms = self.initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 1123, in initial_form_count
    return super().initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 697, in initial_form_count
    return len(self.get_queryset())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 96, in execute_sql
    query_dict['analysis'] = _explain_query(self.connection, q, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 58, in _explain_query
    cur.execute(prefixed_query, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block

2024-10-01 00:22:00,462 (WARNING) - silk.model_factory - Response to request with pk a3f4aed2-2a1f-4fb0-8527-1348a4f24be6 has content type text/javascript but was unable to parse it
2024-10-01 00:22:03,227 (ERROR) - django.request - Internal Server Error: /admin/foundation/language/1/change/
Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 89, in execute_sql
    return self._execute_sql(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1964, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1919, in _changeform_view
    media += inline_formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\helpers.py", line 465, in media
    media = self.opts.media + self.formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 521, in media
    if self.forms:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 207, in forms
    for i in range(self.total_form_count())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 182, in total_form_count
    initial_forms = self.initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 1123, in initial_form_count
    return super().initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 697, in initial_form_count
    return len(self.get_queryset())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 96, in execute_sql
    query_dict['analysis'] = _explain_query(self.connection, q, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 58, in _explain_query
    cur.execute(prefixed_query, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block

2024-10-01 00:23:45,647 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-10-01 00:23:46,475 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:24:00,592 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-10-01 00:24:01,331 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:24:06,411 (WARNING) - silk.model_factory - Response to request with pk 4cc46643-2e4f-4031-a8d0-bc76718ad006 has content type text/javascript but was unable to parse it
2024-10-01 00:24:07,780 (ERROR) - django.request - Internal Server Error: /admin/foundation/language/2/change/
Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 89, in execute_sql
    return self._execute_sql(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1964, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1919, in _changeform_view
    media += inline_formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\helpers.py", line 465, in media
    media = self.opts.media + self.formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 521, in media
    if self.forms:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 207, in forms
    for i in range(self.total_form_count())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 182, in total_form_count
    initial_forms = self.initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 1123, in initial_form_count
    return super().initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 697, in initial_form_count
    return len(self.get_queryset())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 96, in execute_sql
    query_dict['analysis'] = _explain_query(self.connection, q, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 58, in _explain_query
    cur.execute(prefixed_query, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block

2024-10-01 00:26:01,087 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-10-01 00:26:01,930 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:26:14,775 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py changed, reloading.
2024-10-01 00:26:15,538 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
2024-10-01 00:26:43,334 (ERROR) - django.request - Internal Server Error: /admin/foundation/language/2/change/
Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 89, in execute_sql
    return self._execute_sql(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py", line 21, in change_view
    return super().change_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1964, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1919, in _changeform_view
    media += inline_formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\helpers.py", line 465, in media
    media = self.opts.media + self.formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 521, in media
    if self.forms:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 207, in forms
    for i in range(self.total_form_count())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 182, in total_form_count
    initial_forms = self.initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 1123, in initial_form_count
    return super().initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 697, in initial_form_count
    return len(self.get_queryset())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 96, in execute_sql
    query_dict['analysis'] = _explain_query(self.connection, q, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 58, in _explain_query
    cur.execute(prefixed_query, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block

2024-10-01 00:26:49,070 (WARNING) - silk.model_factory - Response to request with pk fbf70214-45f4-4c14-b0d7-51a6ecf59d91 has content type text/javascript but was unable to parse it
2024-10-01 00:27:05,920 (ERROR) - django.request - Internal Server Error: /admin/foundation/language/add/
Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "language_id" of relation "foundation_alternativename" does not exist
LINE 1: INSERT INTO "foundation_alternativename" ("language_id", "na...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1961, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1872, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1322, in save_related
    self.save_formset(request, form, formset, change=change)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1310, in save_formset
    formset.save()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 796, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 959, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 1157, in save_new
    return super().save_new(form, commit=commit)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 769, in save_new
    return form.save(commit=commit)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "language_id" of relation "foundation_alternativename" does not exist
LINE 1: INSERT INTO "foundation_alternativename" ("language_id", "na...
                                                  ^

2024-10-01 00:27:11,203 (ERROR) - django.request - Internal Server Error: /admin/foundation/language/2/change/
Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 89, in execute_sql
    return self._execute_sql(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column foundation_alternativename.language_id does not exist
LINE 1: SELECT "foundation_alternativename"."id", "foundation_altern...
                                                  ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\admin.py", line 21, in change_view
    return super().change_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1964, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1919, in _changeform_view
    media += inline_formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\helpers.py", line 465, in media
    media = self.opts.media + self.formset.media
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 521, in media
    if self.forms:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 207, in forms
    for i in range(self.total_form_count())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\formsets.py", line 182, in total_form_count
    initial_forms = self.initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 1123, in initial_form_count
    return super().initial_form_count()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 697, in initial_form_count
    return len(self.get_queryset())
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 96, in execute_sql
    query_dict['analysis'] = _explain_query(self.connection, q, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\silk\sql.py", line 58, in _explain_query
    cur.execute(prefixed_query, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.InternalError: current transaction is aborted, commands ignored until end of transaction block

2024-10-01 00:27:18,699 (WARNING) - silk.model_factory - Response to request with pk 259045f5-75ac-4a2d-a5bc-ab902b1d5ed6 has content type text/javascript but was unable to parse it
2024-10-01 00:27:21,070 (WARNING) - silk.model_factory - Response to request with pk 4c7bcdfc-77e8-4fb4-b850-e07047828cb9 has content type text/javascript but was unable to parse it
2024-10-01 00:27:27,835 (ERROR) - django.request - Internal Server Error: /admin/foundation/language/add/
Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "language_id" of relation "foundation_alternativename" does not exist
LINE 1: INSERT INTO "foundation_alternativename" ("language_id", "na...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1961, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1872, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1322, in save_related
    self.save_formset(request, form, formset, change=change)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1310, in save_formset
    formset.save()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 796, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 959, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 1157, in save_new
    return super().save_new(form, commit=commit)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 769, in save_new
    return form.save(commit=commit)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "language_id" of relation "foundation_alternativename" does not exist
LINE 1: INSERT INTO "foundation_alternativename" ("language_id", "na...
                                                  ^

2024-10-01 00:28:09,987 (ERROR) - django.request - Internal Server Error: /admin/foundation/language/add/
Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column "language_id" of relation "foundation_alternativename" does not exist
LINE 1: INSERT INTO "foundation_alternativename" ("language_id", "na...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1961, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1872, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1322, in save_related
    self.save_formset(request, form, formset, change=change)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\contrib\admin\options.py", line 1310, in save_formset
    formset.save()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 796, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 959, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 1157, in save_new
    return super().save_new(form, commit=commit)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 769, in save_new
    return form.save(commit=commit)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\forms\models.py", line 554, in save
    self.instance.save()
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 891, in save
    self.save_base(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 997, in save_base
    updated = self._save_table(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 1160, in _save_table
    results = self._do_insert(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\base.py", line 1201, in _do_insert
    return manager._insert(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\env\lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "language_id" of relation "foundation_alternativename" does not exist
LINE 1: INSERT INTO "foundation_alternativename" ("language_id", "na...
                                                  ^

2024-10-01 00:30:09,326 (WARNING) - silk.model_factory - Response to request with pk 8a54b008-c7ae-4a5b-99e9-793be2cc4ed2 has content type text/javascript but was unable to parse it
2024-10-01 00:30:13,536 (WARNING) - silk.model_factory - Response to request with pk a40d4ea5-7c8f-412b-bfbf-446de32c1590 has content type text/javascript but was unable to parse it
2024-10-01 00:30:22,768 (WARNING) - silk.model_factory - Response to request with pk 6f22401e-b36d-489c-ad48-e35f2f512dc7 has content type text/javascript but was unable to parse it
2024-10-01 00:30:25,609 (WARNING) - silk.model_factory - Response to request with pk 11a119e8-3662-4be0-b9ed-159873ced4ac has content type text/javascript but was unable to parse it
2024-10-01 00:30:29,625 (WARNING) - silk.model_factory - Response to request with pk 12389ffa-d4f2-4528-9144-0aa20d71f01b has content type text/javascript but was unable to parse it
2024-10-01 00:30:30,984 (WARNING) - silk.model_factory - Response to request with pk bd226e34-259d-40d5-8dd3-3f2da989d6b9 has content type text/javascript but was unable to parse it
2024-10-01 00:30:34,509 (WARNING) - silk.model_factory - Response to request with pk 00899cf0-b9cd-4755-bfdd-feb26db7dde5 has content type text/javascript but was unable to parse it
2024-10-01 00:30:38,191 (WARNING) - silk.model_factory - Response to request with pk 82b389ad-6bff-41ea-b5f6-a396dde9eef3 has content type text/javascript but was unable to parse it
2024-10-01 00:30:39,783 (WARNING) - silk.model_factory - Response to request with pk 96c23328-4cab-476e-8cd6-75f7ca429b1c has content type text/javascript but was unable to parse it
2024-10-01 00:30:41,434 (WARNING) - silk.model_factory - Response to request with pk 975d1d9c-4ce3-4270-961a-40475d9f3ed2 has content type text/javascript but was unable to parse it
2024-10-01 00:30:42,931 (WARNING) - silk.model_factory - Response to request with pk a4b6dfa7-9d18-4bcc-a3dd-b7fa00034724 has content type text/javascript but was unable to parse it
2024-10-01 00:31:17,260 (WARNING) - silk.model_factory - Response to request with pk 3dbbce30-bdd7-499b-bb07-d3793bed412a has content type text/javascript but was unable to parse it
2024-10-01 00:31:25,799 (WARNING) - silk.model_factory - Response to request with pk c1f35c0a-86f8-4a73-ac50-f3c5b3692999 has content type text/javascript but was unable to parse it
2024-10-01 00:34:55,341 (INFO) - django.utils.autoreload - C:\Users\Kompiuteris\Downloads\Django 3- Resources\storefront3\foundation\migrations\0004_alter_alternativename_options_and_more.py changed, reloading.
2024-10-01 00:34:56,171 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
